# Generated by Django 5.1 on 2024-08-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teethapp', '0005_mediauploadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediauploadmodel',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
