# Generated by Django 5.1 on 2024-08-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teethapp', '0006_mediauploadmodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediauploadmodel',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediauploadmodel',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
