# Generated by Django 5.1 on 2024-08-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teethapp', '0008_mediauploadmodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediauploadmodel',
            name='memo',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
